export const ADJUST_CUR_WEEK = 'adjustCurWeek'
export const ADJUST_CUR_WEEK_FROM_SERVER = 'adjustCurWeekFromServer'
export const PROXY_SCHOOL_APP_AJAX = 'proxySchoolAppAjax'
export const INIT_CLASS_LIST_OPTIONS = 'initClassListOptions'
export const GET_UPDATE_INFO = 'getUpdateInfo'
